[bot]
token = "bot.token"                                 # The Discord bot token being used. Do not share this!
key = "$"                                           # The command prefix used by the bot.
used_emails = "used_emails.txt"                     # The filename for the file that stores previously used emails.
warn_emails = "exchange_emails.txt"                 # The filename for a file (not needed) for alerting mods if used.
moderator_email = "discordauthentemail@gmail.com"   # The moderator email to contact in the sent email

[email]
sample = "accountid"                                # The sample username given by vhelp. Will also be blacklisted.
domain = "gmail.com"                                # The email domain checked against (i.e. Gmail would be gmail.com).
from = "example@gmail.com"                          # The email account used by the bot to send emails.
password = "password"                               # The password for the email account. Required to login.
subject = "Verification"                            # The subject of the emails being sent by the bot.
server = "smtp.gmail.com"                           # The SMTP server emails are sent from. The Gmail one is provided.
port = "465"                                        # The port of the SMTP server above. The Gmail one is provided.

[discord]
server_role = "email_verify"                        # The tole given to members who successfully verify.
channel_id = 12341234123412                         # The channel id for the verification channel.
notify_id = 12341234123412                          # The channel id for a channel for bot alerts (i.e. mod-only)
admin_id = 12341234123412                           # The user if for a user to ping if an email is already used
author_name = "User"                                # The name sent addressing the person in the email
